package DayA5_0308;

public class ExceptionEx9 {
	public static void main(String[] args) {
		throw new RuntimeException();
//		try {
//			Exception e = new Exception("고의로 발생시킴");
//			throw e;
//			// throw new Exception("고의로 발생"); <= 위에 두줄과 같음
//		} catch (Exception e) {
//			// TODO: handle exception
//			System.out.println("에러 메세지 : " + e.getMessage());
//			e.printStackTrace();
//		}
//		System.out.println("프로그램 정상 종료");
	}
}
